version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app 
    command: go run main/main.go
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: amogus
  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
